<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Per-center letterhead configuration. Each BITAC center can have its own
 * Bangla name, ministry tag, address, contact info, and logo files — all of
 * which feed into the PDF letterhead generated by BitacLetterhead.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('centers', function (Blueprint $table) {
            $table->string('name_bn', 200)->nullable()->after('name');
            $table->string('caption_en', 200)->nullable()->after('name_bn');
            $table->string('ministry_bn', 200)->nullable()->after('caption_en');
            $table->string('government_bn', 200)->nullable()->after('ministry_bn');
            $table->string('address_bn', 300)->nullable()->after('government_bn');
            $table->string('phone_bn', 120)->nullable()->after('phone');
            $table->string('fax_bn', 120)->nullable()->after('phone_bn');
            $table->string('website', 120)->nullable()->after('email');
            $table->string('logo_left_path')->nullable()->after('website');
            $table->string('logo_right_path')->nullable()->after('logo_left_path');
            $table->string('letterhead_color', 16)->default('#1e40af')->after('logo_right_path');
        });

        // Seed Dhaka HQ (center #1) with the official BITAC letterhead text the user
        // shared. Other centers stay blank until an admin fills them in.
        \Illuminate\Support\Facades\DB::table('centers')
            ->where('id', 1)
            ->update([
                'name_bn'        => 'বাংলাদেশ শিল্প কারিগরি সহায়তা কেন্দ্র (বিটাক)',
                'caption_en'     => 'BITAC – A Center of Excellence',
                'ministry_bn'    => 'শিল্প মন্ত্রণালয়',
                'government_bn'  => 'গণপ্রজাতন্ত্রী বাংলাদেশ সরকার',
                'address_bn'     => 'বিটাক, ১১৬ (খ), তেজগাঁও শিল্প এলাকা, ঢাকা-১২০৪।',
                'phone_bn'       => '৮৮৭০২৬৬, ৮৮৭০৬৮০',
                'fax_bn'         => '০২-৮৮৭০৭২৮',
                'website'        => 'www.bitac.gov.bd',
            ]);
    }

    public function down(): void
    {
        Schema::table('centers', function (Blueprint $table) {
            $table->dropColumn([
                'name_bn', 'caption_en', 'ministry_bn', 'government_bn',
                'address_bn', 'phone_bn', 'fax_bn', 'website',
                'logo_left_path', 'logo_right_path', 'letterhead_color',
            ]);
        });
    }
};
